# Generated by Django 5.0.3 on 2024-03-29 17:53

import website.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInformation',
            fields=[
                ('uuid', models.CharField(default=website.utils.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('qr_code', models.ImageField(blank=True, editable=False, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
